### ISSUE TITLE
E2E Key sharing: Add keyshare request dialogs on mobile application

### ISSUE THREAD

**Issue by giomfo** [vector-im/riot-meta#113]
If you log in on a new device, you should get "do you want to share keys with the device?" on the other devices.

See the current web implementation here: https://github.com/matrix-org/matrix-react-sdk/pull/996 

Use the same design:
![screen shot 2017-10-05 at 17 41 56](https://user-images.githubusercontent.com/8969772/31237576-a4c6cf12-a9f7-11e7-9d14-8618ad375a79.png)
![screen shot 2017-10-05 at 17 42 16](https://user-images.githubusercontent.com/8969772/31237578-a6ecae10-a9f7-11e7-9f33-14d9b650f950.png)

**Comment by manuroe** [comment]
PRs behind the hood:
https://github.com/matrix-org/matrix-js-sdk/pull/468
https://github.com/matrix-org/matrix-js-sdk/pull/455
https://github.com/matrix-org/matrix-js-sdk/pull/454

and perhaps:
https://github.com/matrix-org/matrix-js-sdk/pull/449
