### ISSUE TITLE
E2E mobile parity with web

### ISSUE THREAD

**Issue by manuroe** [vector-im/riot-meta#120]
Here is the non exhaustive list of PRs that must be applied on mobile code:
- Remove m.new_device support: https://github.com/matrix-org/matrix-js-sdk/pull/483
- device_one_time_keys_count : https://github.com/matrix-org/matrix-js-sdk/pull/493
- EventDecryptionResult: matrix-org/matrix-js-sdk#523

**Comment by manuroe** [comment]
iOS PRs:
- https://github.com/matrix-org/matrix-ios-sdk/pull/421
- https://github.com/matrix-org/matrix-ios-sdk/pull/425

**Comment by ylecollen** [comment]
Android PRs
https://github.com/matrix-org/matrix-android-sdk/pull/219
