### ISSUE TITLE
iOS and Android missing support for widget URL templates / interpolation

### ISSUE THREAD

**Issue by rxl881** [vector-im/riot-meta#125]
The mobile apps do not currently support widget URL interpolation. This is required for widgets such as tradingview (currently live on /develop and /app).

The main intent of this feature is for variables, either from the widget data object, or from the current user / room props. to be substituted in to the widget URL and passed down to the widget for rendering. 

An example URL template looks like this (in JS):
```
const widgetBaseUrl = '/tradingView.html?exchangePair=$pair&dateRange=$dateRange';
```

The widget data object would be set with something like this:
```
data: {
    pair: pair,
    dateRange: dateRange,
},
```

And the riot-web code for URL template interpolation can be found here -
https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/components/views/rooms/AppsDrawer.js#L107-L151

Can you please look at adding this feature to the mobile apps asap. Please let me know if you need any help or further information.

**Comment by rxl881** [comment]
Thanks very much for adding this @manuroe.

@ylecollen is this on your "radar" for android too?

Thanks.

**Comment by ylecollen** [comment]
@rxl881 
it is fixed on android too.

**Comment by rxl881** [comment]
Great! Thanks Yannick 👍
