### ISSUE TITLE
Render sticker events in the timeline

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-meta#146]
This work is scoped to _rendering only_ - we need all Riot clients to render sticker events properly in the timeline before we launch :smile: 

We can follow up adding the ability to send stickers to the mobile clients later.

### Key features
- Render the sticker in the timeline

### Nice to have
- When the sticker is selected, also show the sticker description in a pop up bubble that appears above/below the sticker (depending on where the sticker is on the screen). We would _really like_ this feature, but not if it means we can't deliver the key feature within the March 30 sprint.

**Comment by lampholder** [comment]
Selected view; no description:

![image](https://user-images.githubusercontent.com/1922197/37589222-82eb247e-2b5c-11e8-943e-0e1bb39af6b5.png)

**Comment by lampholder** [comment]
Selected view; with description (above and below):

Key details:
- description appears above or below sticker (in order to be visible)
- description does not need to change its position with scroll
- description sits on top of a full width 100% opaque background-coloured rectangle (to avoid an avatar floating next to the description and it looking like that person _said_ the image description)


![image](https://user-images.githubusercontent.com/1922197/37589286-ae14ca38-2b5c-11e8-8a76-5352b17c1e4e.png)

![image](https://user-images.githubusercontent.com/1922197/37589322-cbcb66ae-2b5c-11e8-8e75-c1f20fd0cc06.png)

**Comment by lampholder** [comment]
Outstanding items:
- link to the event spec
- confirm with Amandine/Matthew that they're happy with the above for iOS
- confirm with Amandine/Matthew that they're happy with the above for Android
    - this is more controversial, since Android doesn't have the grey speech bubble overlay as part of its UX already

**Comment by rxl881** [comment]
Thanks Tom. For the record, the PR with the sticker message info. is - https://github.com/matrix-org/matrix-doc/pull/1158

**Comment by manuroe** [comment]
There are stickers events after this event: https://matrix.to/#/!tAMgPDeOawUJMkFXVZ:matrix.org/$1521649426549165RCzAn:matrix.org

**Comment by heitorPB** [comment]
PR matrix-org/matrix-doc#1158 was [merged into master](https://github.com/matrix-org/matrix-doc/commit/8d05f80cecfcc4eba78e041aaba8f6ff482864da).
Matrix now has some kind of sticker specification.
It is vague enough to support animated stickers, i think. But it says nothing about sticker packs.
