### ISSUE TITLE
Send Stickers

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-meta#151]
It should look like this (on android at least):

![google pixel 2 10](https://user-images.githubusercontent.com/1922197/39585578-153eb116-4eed-11e8-9d1f-34d834ce5f33.png)

Settings cog view tbd (though it will be the existing scalar stuff as per riot web but in a web view)

**Comment by turt2live** [comment]
Is this just a web view? I'm very curious as to the implementation here for obvious reasons.

**Comment by manuroe** [comment]
@turt2live, yes. The sticker picker is a matrix app.

**Comment by manuroe** [comment]
This feature implies 4 screens changes on mobile:
 - a new "Send Sticker" item to the paperclip menu (this menu does not exist yet on iOS)
 - a new webview screen showing the picker
 - a new sticker packs configuration screen (you open it by tapping on the setting button of the picker)
 - the integration manager must list the sticker pack widget. This is a user widget whereas the integration manager used to display room widgets only

**Comment by manuroe** [comment]
The matrix API v2 spec containing the Widget PostMessage API is available at https://docs.google.com/document/d/1uPF7XWY_dXTKVKV7jZQ2KmsI19wn9-kFRgQ1tFQP7wQ/edit?usp=sharing.

**Comment by manuroe** [comment]
@rxl881,

Here are the issues I met while integration the sticker picker on iOS. Compiling them into a comment is better than nothing: 

- [ ] bad render of the picker on iOS. Need to rotate the device to fix it.
- [ ] `stateKey` instead of `state_key` in the sticker picker widget event in user's account data
- [ ] `widgetData` instead of `data` in post message API request for action `m.sticker`
- [ ] no `requestId` in this request
- [ ] no widget name for the sticker picker

**Comment by rxl881** [comment]
Bad rendering of stickerpack assets on narrow screens should now be fixed

![screen shot 2018-05-09 at 16 21 59](https://user-images.githubusercontent.com/6763606/39823722-8ee0158e-53a5-11e8-802e-75ae3ff593e7.png)

**Comment by rxl881** [comment]
Bad render of the sticker picker should also be fixed on iOS / webkit browsers (pending the . redeploy shortly). However, I don't have a physical device to test with, so please let me know if this still persists.

**Comment by rxl881** [comment]
Sticker picker widget name should now be fixed on /develop / scalar-staging

**Comment by rxl881** [comment]
State key should now be correct format ('state_key').

**Comment by manuroe** [comment]
Other issues on iOS:
- [ ] stickers list is not fullscreen (https://matrix.org/_matrix/media/v1/download/matrix.org/APPeSrkrbPhSjoVlfasqQkLF)
- [ ] no smooth deceleration when scrolling stickers list (missing `-webkit-overflow-scrolling: touch;`?)
- [ ] the search input box is activated wherever you tap on the screen the first time

**Comment by SBiOSoftWhare** [comment]
> stickers list is not fullscreen

There is a fix height of 245px for CSS class `mw_stickerpicker`.

> no smooth deceleration when scrolling stickers list (missing -webkit-overflow-scrolling: touch;?)

Yes adding `-webkit-overflow-scrolling: touch;` to CSS class `mw_stickerpicker` enable smooth deceleration on iOS.

**Comment by bmarty** [comment]
Hi @rxl881 ,

Here's my feedback after integration of sending Sticker on Android:

- [ ] The send sticker screen is limited in height (same than on iOS)
![send a sticker](https://user-images.githubusercontent.com/3940906/40351767-7df54d5e-5dad-11e8-9403-571250e365a9.png)

- [ ] The Manage integrations web page is not displayed with mobile style
![manageintegration](https://user-images.githubusercontent.com/3940906/40351799-8d869e62-5dad-11e8-9eeb-5d9cdad187dd.png)

- [ ] If I open the page with `screenId` to manage the sticker pack and click on the back action on top right, it open the 'manage integration' page. It should close the scalar app

Benoit

**Comment by Thovthe** [comment]
Some cursory testing indicates all is well on Android does that hold for the other platforms?

Can this be closed?
