### ISSUE TITLE
Design the 'Consent Tool' UX

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-meta#173]
We need a tool that gathers consent from the user. It should explain clearly what they're consenting to, and link to more relevant information where appropriate.

**Comment by lampholder** [comment]
![whatsapp2](https://user-images.githubusercontent.com/1922197/39927932-c00d02e8-552b-11e8-8db2-f662ee446cf3.gif)
(high-res version: https://usercontent.riot.im/2cc803ee-0975-4edc-aa50-fcad98ed775f)

**Comment by lampholder** [comment]
I'm thinking something like this (wording still WIP):
![desktop 7](https://user-images.githubusercontent.com/1922197/39933371-afdad2e2-553a-11e8-9237-ed1f59573103.png)

https://www.figma.com/file/YncKlVcJjTlXSwcdiDYQTgh0/Consent-Tool?node-id=9%3A2

**Comment by lampholder** [comment]
In terms of how this is actually displayed IRL, I think we can get away with the simplest possible thing - horizontal-centre-align the above on the page, and if it scrolls off the bottom then people will have to scroll down to find the 'I Agree' before continuing.

Mobile should just be the same in a web view.

**Comment by ara4n** [comment]
@lampholder the figma URL is 404ing, and it'd be super-useful to have access to the copy here so it can be tweaked...

**Comment by lampholder** [comment]
Weird - I must have set the perms wrong. /me grabs the copy

**Comment by lampholder** [comment]
# Understand how your data is used

The Matrix protocol is designed with your privacy and data soverignty in mind. Because it is a decentralised, federated service with cryptographically-validated message integrity, there are a few important things to know before you use the service:

This homeserver (https://matrix.org) is run and managed by [New Vector Ltd](http://example.com).

## Federation

Matrix homeservers share user data with the wider ecosystem over federation.

- If you send messages or media in a room which has participants from other homeservers, your messaging and media content may be copied to those other homeservers.
- We will erase your data upon your request. We will also forward your request onto federated homeservers. However - these homeservers are outside our span of control, so we cannot guarantee they will erase your data.
- Federated homeservers can be located anywhere in the world, and are subject to local laws and regulations.

## Bridging

Some Matrix rooms are bridged to third-party services, such as IRC networks, twitter or email. When a room has been bridged, your messages and media may be copied onto the bridged service.

- It may not be technically possible to support your management of your data once it has been copied onto a bridged service.
- Bridged services can be located anywhere in the world, and are subject to local laws and regulations.

## Deleting your Messages

Messages will be deleted from the matrix.org database once they can no longer be accessed by any users under the access controls defined by the Matrix protocol.

- If you share a message with another user in any matrix room, that user will have access to the message even if you deactivate your account.
- If you redact a message, the message content will no longer be accessible to users on this homeserver. Redactions only remove message content, your display name and avatar - your username will still be visible.

## Legal Basis for Processing

Your data is processed for the exclusive purpose of providing messaging services to you. This processing is conducted with your explicit consent (provided below). 
If you should choose to revoke your consent, please deactivate your account and all processing will cease immediately.

If any of the above are unnacceptable to you **do not use the service**.
- [ ] _I have read and understood and agree to the above._

Please review the [full privacy notice](https://example.com) before using this service. 
- [ ] _I have read and understood the full privacy notice and terms and conditions._

You must be at least 16 years old to use this homeserver (https://matrix.org)
- [ ] _I am at least 16 years old._

**Comment by ara4n** [comment]
In general this looks excellent, but i think the erasure semantics are still unclear.  Specifically, we need to spell out that we consider the act of sending a message to be transferring a copy of it to the other participants in the room.

* "We will erase your data on request" should perhaps be clarified as "We will erase your copy of your data on request"?
* Let's call redactions "removal (redaction)" to match riot's UI
* and "Messages will be deleted from the Matrix.org database" should be clarified as "...when all copies of a message have been erased, or within 30 days of being removed by a redaction. Erased messages are never shared with other users".

I suggest we scribble on a google doc to iterate on it.

**Comment by ara4n** [comment]
Switching to https://docs.google.com/document/d/1hQbTHGnkN4yx3B3pHe4gK9iQ4uPZm0kQdmRNjqV1agE/edit#heading=h.v78h0trvpwae

**Comment by lampholder** [comment]
Go for it :)

The wording was largely (albeit fairly thought through) placeholder - before we dig in too deep, are we happy that all the right things are on the page (I think I am fwiw)?

I guess I'm wondering whether there are any other non-obvious caveats of which people should be abundantly aware before using matrix.org?

**Comment by ara4n** [comment]
Yeah, i think all the right things are there, although i'd quite like to TL;DR the AUP to remind people not to be abusive and that this server operates under UK law.

**Comment by lampholder** [comment]
There is an outstanding question here as to whether this page has a 'Reject' button as well as the 'Accept' button.

If an existing user wants to reject the terms and conditions, it seems reasonable to ask them to go to User Settings and deactivate their account.

For brand new users, the act of rejecting the t's and c's (however executed) should make sure that none of the user's data is processed. Asking them to deactivate their account... actually, that's probably also fine?
