### ISSUE TITLE
Re-request keys on mobile

### ISSUE THREAD

**Issue by manuroe** [vector-im/riot-meta#186]
riot-web PRs:
- matrix-org/matrix-js-sdk#624
- matrix-org/matrix-react-sdk#1791

For reference, the wording on riot-web:

<img width="631" alt="screen shot 2018-06-04 at 15 33 20" src="https://user-images.githubusercontent.com/8418515/40920389-ac47e90a-680c-11e8-88f3-1ccf1af51da8.png">

which will be hard to apply on mobile.

**Comment by manuroe** [comment]
riot-web PRs:
- https://github.com/matrix-org/matrix-js-sdk/pull/624
- https://github.com/matrix-org/matrix-react-sdk/pull/1791

**Comment by manuroe** [comment]
For reference, the wording on riot-web:

<img width="631" alt="screen shot 2018-06-04 at 15 33 20" src="https://user-images.githubusercontent.com/8418515/40920389-ac47e90a-680c-11e8-88f3-1ccf1af51da8.png">

which will be hard to apply on mobile.

**Comment by manuroe** [comment]
There must be a clickable text in the UTC error to "Re-request encryption keys".
Then, this modal must be displayed every time the user taps on it. It acts both as an explaining and a confirmation dialog.

Unlike riot-web, the clickable text does not change once the users rerequest keys.

![simulator screen shot - iphone 5s - 2018-06-08 at 17 16 48](https://user-images.githubusercontent.com/8418515/41166516-b4db636c-6b40-11e8-8417-b5ba26861cff.png)

**Comment by manuroe** [comment]
@lampholder , could you please review the text in the modal. I took it from riot-web but it is a bit verbose for mobile?

**Comment by lampholder** [comment]
Yeah, it is pretty wordy.

How about just:

**Request Sent**
Please check your other devices for key share requests.


It misses out some important information, like the fact that the request won't appear if the the requestee device has already verified the requester, or if you other devices don't _have_ a copy of the key, but that's an awful lot to squeeze into a small space. For now I think probably simpler is better.
