### ISSUE TITLE
Make User Agreement part of the registration flow

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-meta#196]

**Comment by manuroe** [comment]
As of today, once registration is complete, Riot-web displays a modal for the consent page.
It does that by getting an error (with the consent URL) when creating a room with riot-bot.

We should do a similar thing on mobiles and we should integrate it as if it was the last step of the registration flow. The consent page, if required, should appear as the last page of the flow.

So, when a mobile app gets an access token from the HS, it should stay in the registration flow and:
 - create the room with RiotBot and check if GDPR applies
 - if no, go to the home page as before
 - if yes, display the content page into the webview
      - we could add a skip button
 - find a way to detect that the user has given his consent. It may need an update of the [consent page](https://github.com/matrix-org/internal-config/tree/master/synapse/matrix-org/privacy_policy_templates/en). It could be the detection of the redirection to `success.html`.

Note that works well for a new account. It should be affined when an existing user logs in.
