### ISSUE TITLE
MELS Parity

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-meta#20]
If I understand this correctly:

 - Riot Web compresses MELS (room membership events join/leave etc.) so that if there's lots of tedious joining/leaving activity it doesn't take up too much screen space
 - We want this feature to be reproduced in the mobile apps.

**Comment by lampholder** [comment]
@ara4n - is that correct, and do you know if any design work has been done/needs doing?

If it's as I understand it, it probably doesn't require any design work above just copying Riot Web.

**Comment by ara4n** [comment]
I think we can get away without designwork, and just clone the semantics & behaviour for riot-web.
