### ISSUE TITLE
Server Quota Notices in Riot

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-meta#213]
We're going to implement some configurable server quotas for synapse instances, limiting the number of active users (where active == has logged in and hit an API).

We want Riot to be able to represent:
- when you can't log in because the server has hit its active user limit
- when you can't send or receive messages because, even though you're logged in, the server has hit its active user limit and you have somehow been inactive long enough that you're not on the list of allowed active users
- when you are logged in and active, but the server has hit its active user limit and you need to know because some of the people you might want to interact with can't log in due to the limit's having been hit.

**Comment by manuroe** [comment]
Mockup for mobiles: this is the bottom bar version at https://www.figma.com/file/MYGeFa5VuuB1PC7BknJE1r0j/HHS-Server-Notices-Riot-Mobile-(Android).

**Comment by lampholder** [comment]
Here's an svg of the modular logo to use: https://matrix.lant.uk/_matrix/media/v1/download/lant.uk/yaJZmFoeLdgpilxoaxGVjJkB

**Comment by manuroe** [comment]
For tracking, the issue on riot-web is https://github.com/vector-im/riot-web/issues/7091.
