### ISSUE TITLE
Riot Mobile: While typing a reply, it is not clear we are making a reply

### ISSUE THREAD

**Issue by manuroe** [vector-im/riot-meta#218]
On Riot mobile apps, a user can send a reply by selecting a message. The hint in the message composer then changed from `Send a message` to `Send a reply`.

When a user is typing a reply,  the hint `Send a reply` is gone. There is no more visual information that the message the user is typing is for sending a reply.

This is even more confusing when the user started to type a message and then selects a message. Hitting `Send` will send a reply to this selected message.

We need visual information to avoid such confusion.

## UI with the `Send a reply` hint:
![](https://matrix.org/_matrix/media/v1/download/matrix.org/CpepDXbZXCGbXuXpUsWTnIRD)

## The user is typing. They may not know they are replying:
![](https://matrix.org/_matrix/media/v1/download/matrix.org/lqPirUPnNUFJJDCZrdOjMeaL)

**Comment by bmarty** [comment]
Note: there is no 'send' button on Android, it's a picto

**Comment by nadonomy** [comment]
@manuroe I've put together comps for iOS & Android, along with notes on interactions in Zeplin here:

https://zpl.io/amde1xD

**Comment by manuroe** [comment]
The new overlay menu (on develop) makes the reply flow clearer.
