### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-meta#22]
Riot Web has a dark theme.

Riot Mobile does not have a dark theme.

The scope of this project is to enable dark theme on Riot Android and iOS.

**Comment by lampholder** [comment]
@ara4n is this blocked on design work?

**Comment by sabrinaj** [comment]
Started by @jgkamat on Android, see PR https://github.com/vector-im/riot-android/pull/1240

**Comment by giomfo** [comment]
Close the meta issue for the dark theme support.

iOS: some improvements are required here https://github.com/vector-im/riot-ios/issues/1444
