### ISSUE TITLE
Sending a message to myself

### ISSUE THREAD

**Issue by vext01** [vector-im/riot-meta#225]
Hi,

It'd be useful if I could send a message to myself using Riot, for example to (securely, using e2e) share a link from my desktop machine to my android phone.

Currently (in riot web) if I try to start a chat with myself, I get:
![image](https://user-images.githubusercontent.com/604955/46915803-c9174180-cfa8-11e8-8c64-cf291a051469.png)

Thanks

**Comment by aaronraimist** [comment]
Note that this isn’t really a meta issue, as it works on iOS and Android.

Web issue is here: 
https://github.com/vector-im/riot-web/issues/7242

https://github.com/vector-im/riot-web/issues/4933

**Comment by lampholder** [comment]
Since this is tracked in Riot Web and isn't an issue on mobile I'll close this here
