### ISSUE TITLE
E2E: Recovery Setup

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-meta#227]
- [x] Set passphrase (3)
    - [x] Strength validation - using zxcvbn (1)
- [X] Copy recovery key to clipboard
- [x] Download recovery key (1)
- [x] Set up back up with just recovery key without setting a passphrase (1)
- [x] [Log out warning (if you haven't set up recovery)](https://github.com/vector-im/riot-web/issues/7805) (1) (Leaving until e2e backup is out of labs / prompted for at login)

**Comment by nadonomy** [comment]
Direct link to relevant wireframes:

https://docs.google.com/document/d/1TIZarCxP0UHcn52o3YdKrFs_ESB3YvDxvCY_SoY-FUk/edit#bookmark=id.y47xu7m62l1g
