### ISSUE TITLE
key backup: Add a dedicated section to settings

### ISSUE THREAD

**Issue by manuroe** [vector-im/riot-meta#251]
Add a key backup section to the user settings.
Its content depends on the key backup status. Here are some screenshots from riot-web (at the time of writing):

- No backup created yet
<img width="171" alt="screenshot 2019-01-21 at 10 32 16" src="https://user-images.githubusercontent.com/8418515/51466873-7bf6f880-1d6b-11e9-8841-14bcb528cde4.png">

- Backup is up
<img width="339" alt="screenshot 2019-01-21 at 10 42 13" src="https://user-images.githubusercontent.com/8418515/51466875-7c8f8f00-1d6b-11e9-92bc-188a9dc407f7.png">

- Backup is up and running
<img width="283" alt="screenshot 2019-01-21 at 13 46 32" src="https://user-images.githubusercontent.com/8418515/51475606-27f80e00-1d83-11e9-8456-5315c94037bd.png">

- Backup has been created from another device not yet verified:
<img width="401" alt="screenshot 2019-01-21 at 10 43 47" src="https://user-images.githubusercontent.com/8418515/51466874-7c8f8f00-1d6b-11e9-9119-fbb594a9e06d.png">

- Backup deletion confirmation dialog:
<img width="562" alt="screenshot 2019-01-21 at 11 26 41" src="https://user-images.githubusercontent.com/8418515/51477241-19f8bc00-1d88-11e9-83b2-3fed8fc373ed.png">

**Comment by manuroe** [comment]
We need to improve the wording to match "MESSAGE RECOVERY" used in other places:

![](https://matrix.org/_matrix/media/v1/download/matrix.org/GYkgfApahPWsyteXBaJUVzAl)

**Comment by lampholder** [comment]
- No backup created yet:

    ### Secure Message Recovery
    Secure Message Recovery has not been set up.

    [Set up Secure Message Recovery]

---
- Backup is up:

    ### Secure Message Recovery
    Secure Message Recovery has been **correctly set up** for this device.
    All keys have been **backed up**

    Key Backup Version: 3
    Algorithm: m.megolm_backup.v1.curve25519-aes-sha2
    Backup has a **valid** signature from this device

    [ Restore backup ] [ Delete backup ]

---
- Backup is up and running (is in progress):

    ### Secure Message Recovery
    Secure Message Recovery has been **correctly set up** for this device.
    Backing up 1234 keys...

    Key Backup Version: 3
    Algorithm: m.megolm_backup.v1.curve25519-aes-sha2
    Backup has a **valid** signature from this device

    [ Restore backup ] [ Delete backup ]

---
- Backup has been created from another device that is verifiable but not yet verified:

    ### Secure Message Recovery
    Secure Message Recovery is not active on this device.
    To use Secure Message Recovery on this device, verify _Device Name_ now.

    [ Verify ]

    Key Backup Version: 3
    Algorithm: m.megolm_backup.v1.curve25519-aes-sha2
    Backup has a signature from _Device Name_

    [ Restore backup ] [ Delete backup ]

---
- Backup has been created from another device that is not yet verifiable, and trust on decrypt has been implemented:

    ### Secure Message Recovery
    Secure Message Recovery is not active on this device.
    To use Secure Message Recovery on this device, provide your passphrase or recovery key now.

    [ Setup Secure Message Recovery ]

    Key Backup Version: 3
    Algorithm: m.megolm_backup.v1.curve25519-aes-sha2
    Backup has a signature from device with ID: PLACEHOLDR

    [ Restore backup ] [ Delete backup ]

---
- Backup has been created from another device that is not yet verifiable, and trust on decrypt has _not yet_ been implemented:

    ### Secure Message Recovery
    ☠️☠️☠️☠️☠️☠️☠️☠️☠️☠️☠️☠️☠️☠️☠️☠️☠️☠️☠️
    This is pain
    Lets implement trust on decrypt rather than any of the workaround UX we'd need without it pls

**Comment by lampholder** [comment]
I've had an idea for a simpler approach - replace the section heading 'Key Backup' with:

### Secure Message Recovery

Secure Message Recovery ensures you'll always be able to read your encrypted messages by securely storing a backup of your decryption keys on the server.

---
This should contextualise all of the backup stuff within the Secure Message Recovery feature. It's far from perfect, and will require revisiting once we've had a chance to think through this UX in more detail, but is a little better than just copying in the somewhat confusing Key Backup stuff from web into mobile.

@manuroe what do you think?
