### ISSUE TITLE
key backup: logout warning

### ISSUE THREAD

**Issue by manuroe** [vector-im/riot-meta#252]
Advice the end user to backup their e2e keys before logout:
<img width="570" alt="screenshot 2019-01-21 at 10 34 36" src="https://user-images.githubusercontent.com/8418515/51477581-2f221a80-1d89-11e9-9174-ef973b3a81a2.png">

On the other hand, if a backup is active, advertise the key backup recovery for the next login:
<img width="563" alt="screenshot 2019-01-21 at 10 42 55" src="https://user-images.githubusercontent.com/8418515/51477582-2fbab100-1d89-11e9-8eae-563936b2d3b8.png">

**Comment by lampholder** [comment]
We discussed this last night, and thought that:

- If the user has key backup set up:
    - let them log out without showing them a warning
- if the user does _not_ have key backup set up:
    - show them a warning
    - give them the option to download their keys
    - advise them to (and give them a link to) set up key backup before they log out

**Comment by bmarty** [comment]
Just as a remember, we use the verb "sign out" instead of "log out" in all the wording
