### ISSUE TITLE
key backup: recover reminder

### ISSUE THREAD

**Issue by manuroe** [vector-im/riot-meta#255]
Show a banner on the home screen to allow the end user to recover their keys from an existing backup.
That will be useful when they log in on a new device.

**Comment by manuroe** [comment]
In term of design, we can reuse https://github.com/vector-im/riot-meta/issues/254 but with a different wording.

**Comment by lampholder** [comment]
Hmm, are we certain we want to invite newly-logged-in users to restore keys from backup in all circumstances?

**Comment by lampholder** [comment]
How about this:

### Secure Message Recovery

Secure Message Recovery has been set up on your account.

Secure Message Recovery securely backs up your secure message decryption keys to the server. To read your old secure messages on this device, restore from backup now.

[ Restore from backup] [ Not now ]

**Comment by manuroe** [comment]
@lampholder, we were looking for a shorter text like the one for the setup reminder (https://app.zeplin.io/project/5b857c64b1747a2c472290da/screen/5c46041735c1a337cd9253ce).

**Comment by lampholder** [comment]
Right - I'm not totally sure that we _do_ want to prompt people to restore from backup, but if we do:

### Run Secure Message Recovery
to read encrypted message history on this device

Is that short enough?

**Comment by manuroe** [comment]
Yes, thanks!
