### ISSUE TITLE
Onboarding

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-meta#27]
Placeholder overarching issue to track progress on: resolving onboarding issues.

Should likely be decomposed into target sections:
 - registration
 - login
 - landing page
 - autojoin
 - finding friends

**Comment by lampholder** [comment]
I've scoped out https://github.com/vector-im/riot-meta/issues/59 for Riot Web which describes how we're tackling Guest access, which in turn is having an impact on the registration process.

None of this impacts the mobile apps :)

**Comment by lampholder** [comment]
This issue is too meta meta for me; closing. @giomfo I think something like #59 is the right sort of size - this is too big to be useful IMHO :)

**Comment by giomfo** [comment]
Agree with you, except that #59 description should not be limited to Riot web (even if Guest access is not supported on mobile clients ;)).
For example, all the listed user flow may concern all the Riot clients...
