### ISSUE TITLE
Expose the Scalar interface (integrations manager)

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-meta#3]
The Scalar (integrations manager) interface is already exposed in Riot Web:

![screen shot 2017-03-22 at 15 03 14](https://cloud.githubusercontent.com/assets/1922197/24204548/badbc154-0f10-11e7-9dc6-98cc54e5ae12.png)
![screen shot 2017-03-22 at 15 02 54](https://cloud.githubusercontent.com/assets/1922197/24204552/bdcac81a-0f10-11e7-93ab-f0cc347bd3d9.png)
![screen shot 2017-03-22 at 15 03 03](https://cloud.githubusercontent.com/assets/1922197/24204554/bf880f46-0f10-11e7-82f4-cb8f697f678f.png)

The objective here is to expose that interface in the Android and iOS clients, too. This should be achieved using Scalar's ability to serve up HTML to be rendered on the client.

**Comment by lampholder** [comment]
Linking for reference:
 - https://github.com/vector-im/vector-web/pull/1928
 - https://github.com/vector-im/vector-ios/issues/726
 - https://github.com/vector-im/vector-android/issues/630

**Comment by ara4n** [comment]
In practice this is just shoving a webview which can be triggered from RoomSettings which loads scalar.vector.im, and will need to implement the same postMessage API that web does at https://github.com/matrix-org/matrix-react-sdk/blob/master/src/ScalarMessaging.js
