### ISSUE TITLE
Allow full set of emoji reactions

### ISSUE THREAD

**Issue by Mikaela** [vector-im/riot-meta#304]
The current set of reaction emojis are directly copied from GitHub (or at least are identical). I wish the full set of emojis was available like for example in Keybase and GitLab which both provide a search. They would be more expressive while I think the GitHub set is lacking in many cases.

For example there is no way to express sadness with them, the closest would be :confused:, but people may be sad on something without being confused about it. Personally again I use cat emojis more often in instant messengers than the generic smileys and would use a purple heart instead of a red one. I also have no idea when someone would use :rocket: or :eyes:.

**Comment by jryans** [comment]
This work is already planned as mentioned in [Riot blog post](https://medium.com/@RiotChat/%EF%B8%8Fmessage-editing-%EF%B8%8F-reactions-5cffec8f71a2). It's already available in RiotX for Android, and it will come to the other platforms soon:

* [Riot Web](https://github.com/vector-im/riot-web/issues/9483)
* [Riot iOS](https://github.com/vector-im/riot-ios/issues/2370)

**Comment by tulir** [comment]
This is done now
