### ISSUE TITLE
UX rework: Merge Room Directory into Rooms

### ISSUE THREAD

**Issue by giomfo** [vector-im/riot-meta#54]
related to #53

**Comment by jeangb** [comment]
### - Android: 
* if you scroll too fast in the room directory section, the pagination will be stopped early. It will be necessary to scroll up then scroll down to trigger again the pagination.

**Comment by jeangb** [comment]
Test automation:

- [ ] Write tests for Android
- [ ] Write tests for iOS

**Comment by manuroe** [comment]
> Not sure if the right riot-meta issue, but when I hit DECLINE after hitting a room in the ROOM DIRECTORY, I landed in the homepage.
@jeangb : fixed on iOS

**Comment by jeangb** [comment]
### - iOS
Ok for the "decline whose redirect to homepage".
It seems I can't scroll very far on the ROOM DIRECTORY list in Rooms tab, I'm quickly stopeed after 20 rooms, unlike Browse directory from Unified Search.

**Comment by Matrixcoffee** [comment]
Please reconsider this design choice, and place the room directory in its own activity. With all the additional elements, the remaining space for the rooms becomes painfully small.

![screenshot_2017-05-30-08-27-09](https://user-images.githubusercontent.com/21172059/27002333-bae03bec-4dce-11e7-8274-aafb2a9d1f20.png)

It is even worse in landscape mode:

![screenshot_2017-05-30-11-50-05](https://user-images.githubusercontent.com/21172059/27002336-cac37a9c-4dce-11e7-9396-ce740c3ae794.png)

**Comment by giomfo** [comment]
Keep open this issue for the Matrixcoffee's remark.
