### ISSUE TITLE
UX rework: Add favourites screen

### ISSUE THREAD

**Issue by giomfo** [vector-im/riot-meta#56]
Related to #53.

- List favourites rooms
- Support drag&drop to order them

**Comment by jeangb** [comment]
- Android:

Seen with @ylecollen, we could avoir to drag n drop a room when there is only one of them because of this:
![drag and drop on 1 room](https://cloud.githubusercontent.com/assets/22364949/25959934/b8f8e038-3675-11e7-8927-4785bb2e99bf.jpg)

**Comment by jeangb** [comment]
Validated in 0.6.10-dev
