### ISSUE TITLE
Ability to join room by ID or alias

### ISSUE THREAD

**Issue by giomfo** [vector-im/riot-meta#65]
Add the option "Join Room" in the displayed actions list when the user presses the (+) button on the`Home` and the `Rooms` screen.

**Comment by jeangb** [comment]
About the join option in the rooms tab, is it still current ? because it's not developed in riot-ios neither in riot-android.

**Comment by jeangb** [comment]
### - Android & iOS:

Join option from ROOMS tab is missing.

**Comment by jeangb** [comment]
Test automation:
- [ ] Write tests for Android
- [ ] Write tests for iOS

**Comment by manuroe** [comment]
> Join option from ROOMS tab is missing.
@jeangb: it is now available
