### ISSUE TITLE
UX Rework: Apply a different colour scheme on each application tab.

### ISSUE THREAD

**Issue by giomfo** [vector-im/riot-meta#72]
All the list look very similar so we want a way to differentiate the screens. We would like to apply a different colour scheme on them as per the colour list below. 
The theme applies to:
- the (+) button when it exists
- the icons in the header
- The icons in the tab bar
- The header on Android

Colour scheme:
Home: Teal (#78CFA5)
Favourites: Indigo (#BD79CC)
People: Orange (#F8A15F)
Rooms: Teal (#78CFA5)

**Comment by AmandineLP** [comment]
Reviewed proposal:
On iOS:
- the (+) button when it exists
- the icons in the header
- the icons in the tab bar

On Android:
- the background of the header only
(i.e. not changing the colour of the (+) nor of the icons in the tab bar)

**Comment by giomfo** [comment]
In order to not introduce a new green colour, the tint colour for the Home and Rooms screens is replaced with SeafoamBlue: 0x62CE9C
