### ISSUE TITLE
UX Rework - Handle tap on sticky headers to scroll to the top

### ISSUE THREAD

**Issue by giomfo** [vector-im/riot-meta#73]
Add chevron as on the original design of the room list
Behaviour:
Click once => jump to the top
Click on the chevron => collapse/expand

**Comment by AmandineLP** [comment]
Update:
On iOS:
- Click once => jump to the top
- Click on the chevron => collapse/expand

On Android:
- Click on the header or the chevron => expand/collapse

Sections should collapse from the bottom: if all sections are collapsed, all headers are grouped at the top.

**Comment by giomfo** [comment]
Update:

On both platforms:
- Click once => jump to the top

We're giving up on the expand/collapse behaviour of the sticky headers

**Comment by jeangb** [comment]
Test automation:
- [ ] Android

- iOS: difficult to implement due to the fact that iOS automation framework XCUItest see all the elements even if they are hidden

**Comment by jeangb** [comment]
### - Android

* A tap on a sticky header is ineffective in People tab when "Matrix contacts only" is checked. (On a Samsung Galaxy S4 - Android 4.4.2)

**Comment by giomfo** [comment]
We consider this issue as done.

An iOS issue has been filed to track the wrong behaviour of the sticky headers.
(https://github.com/vector-im/riot-ios/issues/1232)
