### ISSUE TITLE
UX Rework: Add home page

### ISSUE THREAD

**Issue by giomfo** [vector-im/riot-meta#75]
The Home screen should have the following sections:
Invite, Favourites, People, Rooms, Low Priority, Historical

Each rooms section is displayed on only one row.
Each room is represented by its avatar and its display name. The 3 existing badges (unread, direct, encrypted) are kept.

Long tap on a room should show the same menu as today.

**Comment by AmandineLP** [comment]
Notes:
1. Favourites should be ordered by activities on the home page
2. We are considering other ways of highlighting direct chats. More info to come.

**Comment by giomfo** [comment]
@sabrinaj: The `Historical` section will be tracked by the dedicated issue #64.
Can we move this issue in the `Done` column for the Android project?

On IOS, the edition mode is still missing.

**Comment by sabrinaj** [comment]
I left it open in case the way of highlighting direct chats changes but I guess we can create a new issue for it later.

**Comment by jeangb** [comment]
### Test automation:

- [x] Android
- [ ] iOS: impossible to test the enabled / direct chat / badges icons

**Comment by giomfo** [comment]
iOS: open the edition menu of the room on long press.
