### ISSUE TITLE
UX Rework: Duplicate favourited rooms across dedicated tabs

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-meta#77]
Rooms which are favourited should be displayed both on the favourite tab and on their dedicated tab. I.e.:
- a favourited direct chat is listed in Favourites and People
- a favourited room (as in not a direct chat) is listed in Favourites and Rooms

Low priority rooms are **not** duplicated, and only listed on the home page.

**Comment by giomfo** [comment]
Done on iOS

**Comment by ylecollen** [comment]
done on android

**Comment by jeangb** [comment]
Amandine: about low priorities direct chats, do they need to be listed both in the Home page and the People tabs ?

**Comment by AmandineLP** [comment]
Nope, low priority rooms are **only** listed in the low priority section, not duplicated in other tabs.

**Comment by jeangb** [comment]
### - Android & iOS

Currently, low priorities direct chats are listed in People tabs too, and should only be listed on the home page.

**Comment by jeangb** [comment]
Tests automation:
- [X] Write down tests for Android
- [ ] Write down tests for iOS

**Comment by jeangb** [comment]
### - iOS
- Ok, low priorities direct chat are no longer listed in People tab
