### ISSUE TITLE
Read markers should be synchronised across clients

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-meta#8]
Read markers are not synchronised across clients, and they should be :)

The detailed thinking on this is here:
 - https://github.com/vector-im/riot-web/issues/1159
 - https://docs.google.com/document/d/1f9UJdoB7EG7SaUTpumpqOyV6PvVlZnTi8mLGNkNp6n4

**Comment by lampholder** [comment]
Linking for reference:
 - https://github.com/vector-im/riot-web/issues/1159
 - https://github.com/vector-im/riot-ios/issues/395
 - https://github.com/vector-im/riot-android/issues/228

**Comment by giomfo** [comment]
In terms of read marker implementation on mobile, the conclusion is as follow:

- The implementation should follow the web one, i.e. add the line allowing to visualise the read marker, differentiate the read marker position from the read receipt, add appropriate buttons to jump to last unread and to the bottom of the page
- An idea is to leverage the read-only view used when clicking on a permalink to do so:
click on ‘jump to last unread message’ opens the last unread message in the read-only view,
the view is switched back to read-write when all messages are caught-up or when clicking on ‘jump to the bottom of the page’
