### ISSUE TITLE
Widgets on mobile

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-meta#93]
Closely related to https://github.com/vector-im/riot-meta/issues/3, we nowadays support the ability to embed chunks of web UI in rooms as 'widgets'.  On web, I suggest this should just be an overlay of a WebView which can be summoned over the top of the roomview - probably taking up 80% of the height of the device, so it's clear that it's an overlay.  The 'widget overlay' button could be another button in the top right (alongside the search button) perhaps.

The spec for reading the room state to decide which widgets to display is with @kegsay, @superdump and @rxl881 - can one of you (@kegsay?) feed in here to let mobile folks know how to go about showing widgets on mobile?

**Comment by Kegsay** [comment]
https://docs.google.com/document/d/1TiWNDcEOULeRYQpkJHQDjgIW32ohIJSi5MKv9oRdzCo/edit

It's a public document.
