### ISSUE TITLE
Encryption Issues:

### ISSUE THREAD

**Issue by GIJack** [vector-im/riot-meta#99]
With the room encryption issues, ever new login makes a new key pair. This makes verifying keys incredibly difficult for those who sign in and out.

Better management of key-pairs is needed for encryption:

Recommendation is being able to import and export keys, perhaps being able to save keys in a file encrypted by the password, and re-imported.

There also should be some mechanism for syncing keys across all devices.

**Comment by uhoreg** [comment]
see also https://github.com/vector-im/riot-web/issues/4104 and https://github.com/vector-im/riot-web/issues/2714

**Comment by ara4n** [comment]
this is basically a dup of https://github.com/vector-im/riot-web/issues/2714
